### ISSUE TITLE
RetryBackoff may overflow if redis cann't connect

### ISSUE THREAD

**Issue by YiLinice** [go-redis/redis#1492]
panic: invalid argument to Int63n

goroutine 47 [running]:
golang.org/x/exp/rand.(*Rand).Int63n(...)
	/root/go/pkg/mod/golang.org/x/exp@v0.0.0-20200821190819-94841d0725da/rand/rand.go:115
golang.org/x/exp/rand.Int63n(...)
	/root/go/pkg/mod/golang.org/x/exp@v0.0.0-20200821190819-94841d0725da/rand/rand.go:282
github.com/go-redis/redis/v8/internal.RetryBackoff(0x29, 0x7a1200, 0x1e848000, 0x0)
	/root/go/pkg/mod/github.com/go-redis/redis/v8@v8.0.0-beta.10/internal/internal.go:18 +0xc2
github.com/go-redis/redis/v8.(*PubSub).retryBackoff(...)
	/root/go/pkg/mod/github.com/go-redis/redis/v8@v8.0.0-beta.10/pubsub.go:617
github.com/go-redis/redis/v8.(*PubSub).initMsgChan.func1(0xc0001bf180, 0xcf17e0, 0xc0000340e0)
	/root/go/pkg/mod/github.com/go-redis/redis/v8@v8.0.0-beta.10/pubsub.go:516 +0x103
created by github.com/go-redis/redis/v8.(*PubSub).initMsgChan
	/root/go/pkg/mod/github.com/go-redis/redis/v8@v8.0.0-beta.10/pubsub.go:503 +0x93

```
func RetryBackoff(retry int, minBackoff, maxBackoff time.Duration) time.Duration {
	if retry < 0 {
		panic("not reached")
	}
	if minBackoff == 0 {
		return 0
	}

	d := minBackoff << uint(retry)
        // d may overflow, and rand.Int63n will panic if d <= 0
	d = minBackoff + time.Duration(rand.Int63n(int64(d)))

	if d > maxBackoff || d < minBackoff {
		d = maxBackoff
	}

	return d
}
```

**Comment by wziww** [comment]
Actually i do think two problem lead to this issue.
- `d` val overflow
- `initAllChan` func has not handle with the `net.OpError` errors 
resulting in looping too many times to call the `RetryBackoff` func in wrong way.

**Comment by mrsinham** [comment]
Hello, we still have the problem here: 

```panic: invalid argument to Int63n
goroutine 438826 [running]:
math/rand.(*Rand).Int63n(0xc000448570, 0xf424000000000000, 0xc000dedd60)
/home/travis/.gimme/versions/go1.15.linux.amd64/src/math/rand/rand.go:111 +0x11d
github.com/go-redis/redis/v8/internal/rand.Int63n(...)
/home/travis/gopath/pkg/mod/github.com/go-redis/redis/v8@v8.3.2/internal/rand/rand.go:17
github.com/go-redis/redis/v8/internal.RetryBackoff(0x29, 0x7a1200, 0x1e848000, 0x0)
/home/travis/gopath/pkg/mod/github.com/go-redis/redis/v8@v8.3.2/internal/internal.go:18 +0x57
github.com/go-redis/redis/v8.(*baseClient).retryBackoff(...)
/home/travis/gopath/pkg/mod/github.com/go-redis/redis/v8@v8.3.2/redis.go:368
github.com/go-redis/redis/v8.(*baseClient).process.func1(0x17517a0, 0xc0030601b0, 0x175ea80, 0x598b1c0, 0x0, 0xc0014b6700)
/home/travis/gopath/pkg/mod/github.com/go-redis/redis/v8@v8.3.2/redis.go:331 +0x175
github.com/go-redis/redis/v8/internal.WithSpan(0x17517a0, 0xc0030601b0, 0x153f51a, 0x7, 0xc000deded8, 0x0, 0x0)
/home/travis/gopath/pkg/mod/github.com/go-redis/redis/v8@v8.3.2/internal/util.go:67 +0x262
github.com/go-redis/redis/v8.(*baseClient).process(0xc000304300, 0x17517a0, 0xc0030601b0, 0x175f300, 0xc0017438c0, 0xc0014df680, 0xc002579f28)
/home/travis/gopath/pkg/mod/github.com/go-redis/redis/v8@v8.3.2/redis.go:329 +0xe5
github.com/go-redis/redis/v8.hooks.process.func1(0x158e4b0, 0x0)
/home/travis/gopath/pkg/mod/github.com/go-redis/redis/v8@v8.3.2/redis.go:55 +0x4c
github.com/go-redis/redis/v8.hooks.withContext.func1(0xc0017439e0, 0xc003060240)
/home/travis/gopath/pkg/mod/github.com/go-redis/redis/v8@v8.3.2/redis.go:138 +0x27
created by github.com/go-redis/redis/v8.hooks.withContext
/home/travis/gopath/pkg/mod/github.com/go-redis/redis/v8@v8.3.2/redis.go:138 +0xa5
```

Do you know what is causing the issue?
