### ISSUE TITLE
Panic after redis connection lost (v2.3.2)

### ISSUE THREAD

**Issue by firstrow** [go-redis/redis#165]
After redis-server is stopped my app have a panic at gopkg.in/redis.v2/pool.go:220
Is this redismq issue or go-redis?

Just for debug I wrote deffered func to recover and that fixed problem
``` go
func (p *connPool) remove(cn *conn) error {
      defer func() {
		if r := recover(); r != nil {
			log.Fatal("Error")
			return nil
		}
	}()
	p.conns.Remove(cn.elem)
	cn.elem = nil
	if !cn.inUse {
		p.idleNum--
	}
	return cn.Close()
}
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x10 pc=0x4249321]

goroutine 29 [running]:
gopkg.in/redis%2ev2.(*connPool).remove(0xc8200706c0, 0xc8200da070, 0x0, 0x0)
        /Users/andrew/Code/go/src/gopkg.in/redis.v2/pool.go:220 +0x41
gopkg.in/redis%2ev2.(*connPool).Remove(0xc8200706c0, 0xc8200da070, 0x0, 0x0)
        /Users/andrew/Code/go/src/gopkg.in/redis.v2/pool.go:213 +0xaf
gopkg.in/redis%2ev2.(*baseClient).removeConn(0xc820076690, 0xc8200da070)
        /Users/andrew/Code/go/src/gopkg.in/redis.v2/redis.go:83 +0x54
gopkg.in/redis%2ev2.(*baseClient).conn(0xc820076690, 0xc820098100, 0x0, 0x0)
        /Users/andrew/Code/go/src/gopkg.in/redis.v2/redis.go:33 +0xde
gopkg.in/redis%2ev2.(*baseClient).run(0xc820076690, 0x5264460, 0xc820098100)
        /Users/andrew/Code/go/src/gopkg.in/redis.v2/redis.go:103 +0x30
gopkg.in/redis%2ev2.(*baseClient).Process(0xc820076690, 0x5264460, 0xc820098100)
        /Users/andrew/Code/go/src/gopkg.in/redis.v2/redis.go:96 +0x43
gopkg.in/redis%2ev2.(*Client).SetEx(0xc820092020, 0xc8200121e0, 0x2f, 0x3b9aca00, 0x464d360, 0x4, 0x2f)
        /Users/andrew/Code/go/src/gopkg.in/redis.v2/commands.go:445 +0x1c2
github.com/xxx/xxx/redismq.(*Consumer).startHeartbeat.func1(0xc8200157a0, 0xc82006e070)
        /Users/andrew/Code/go/src/github.com/xxx/xxx/redismq/consumer.go:177 +0x25f
created by github.com/xxx/xxx/redismq.(*Consumer).startHeartbeat
        /Users/andrew/Code/go/src/github.com/xxx/xxx/redismq/consumer.go:184 +0x5d
```

**Comment by vmihailenco** [comment]
This is https://github.com/go-redis/redis/issues/135. Can you upgrade to v3? I will send PR for redismq.

**Comment by firstrow** [comment]
I'm really appreciate your help. Thanks.

**Comment by firstrow** [comment]
@vmihailenco - I've already did support of redis v3 to redismq. will send them PR soon.
Thanks.

**Comment by firstrow** [comment]
Here it is.
https://github.com/adjust/redismq/pull/24/files
