### ISSUE TITLE
bad pointer in parseReply

### ISSUE THREAD

**Issue by SergeyTsalkov** [go-redis/redis#175]
I've been getting this crash..

```
runtime: bad pointer in frame gopkg.in/redis%2ev3.(*BoolCmd).parseReply at 0xc8213a3cb8: 0x3
fatal error: invalid stack pointer

runtime stack:
runtime.throw(0xadd830, 0x15)
        /usr/local/go/src/runtime/panic.go:527 +0x90 fp=0x7fa2dd7f96f8 sp=0x7fa2dd7f96e0
runtime.adjustpointers(0xc8213a3c58, 0x7fa2dd7f9870, 0x7fa2dd7f9a60, 0xce4ad8)
        /usr/local/go/src/runtime/stack1.go:438 +0x2d4 fp=0x7fa2dd7f97f0 sp=0x7fa2dd7f96f8
runtime.adjustframe(0x7fa2dd7f9980, 0x7fa2dd7f9a60, 0xc800000001)
        /usr/local/go/src/runtime/stack1.go:505 +0x1b5 fp=0x7fa2dd7f98a8 sp=0x7fa2dd7f97f0
runtime.gentraceback(0x40f660, 0xc8213a3c08, 0x0, 0xc8204fed80, 0x0, 0x0, 0x7fffffff, 0xb88ce0, 0x7fa2dd7f9a60, 0x0, ...)
        /usr/local/go/src/runtime/traceback.go:336 +0xa69 fp=0x7fa2dd7f99d8 sp=0x7fa2dd7f98a8
runtime.copystack(0xc8204fed80, 0x1000)
        /usr/local/go/src/runtime/stack1.go:616 +0x1a7 fp=0x7fa2dd7f9ac8 sp=0x7fa2dd7f99d8
runtime.shrinkstack(0xc8204fed80)
        /usr/local/go/src/runtime/stack1.go:880 +0x148 fp=0x7fa2dd7f9af8 sp=0x7fa2dd7f9ac8
runtime.markroot(0xc820016000, 0x16a)
        /usr/local/go/src/runtime/mgcmark.go:130 +0x1ac fp=0x7fa2dd7f9b98 sp=0x7fa2dd7f9af8
runtime.parfordo(0xc820016000)
        /usr/local/go/src/runtime/parfor.go:110 +0x1d4 fp=0x7fa2dd7f9c20 sp=0x7fa2dd7f9b98
runtime.gchelper()
        /usr/local/go/src/runtime/mgc.go:1700 +0x56 fp=0x7fa2dd7f9c68 sp=0x7fa2dd7f9c20
runtime.stopm()
        /usr/local/go/src/runtime/proc1.go:1131 +0x146 fp=0x7fa2dd7f9c90 sp=0x7fa2dd7f9c68
runtime.gcstopm()
        /usr/local/go/src/runtime/proc1.go:1321 +0xf8 fp=0x7fa2dd7f9cc0 sp=0x7fa2dd7f9c90
runtime.schedule()
        /usr/local/go/src/runtime/proc1.go:1596 +0x9c fp=0x7fa2dd7f9cf8 sp=0x7fa2dd7f9cc0
runtime.goschedImpl(0xc823003800)
        /usr/local/go/src/runtime/proc1.go:1713 +0x12a fp=0x7fa2dd7f9d10 sp=0x7fa2dd7f9cf8
runtime.gopreempt_m(0xc823003800)
        /usr/local/go/src/runtime/proc1.go:1728 +0x32 fp=0x7fa2dd7f9d20 sp=0x7fa2dd7f9d10
runtime.newstack()
        /usr/local/go/src/runtime/stack1.go:786 +0xa92 fp=0x7fa2dd7f9e98 sp=0x7fa2dd7f9d20
runtime.morestack()
        /usr/local/go/src/runtime/asm_amd64.s:330 +0x7f fp=0x7fa2dd7f9ea0 sp=0x7fa2dd7f9e98

```

```
goroutine 538 [copystack]:
runtime.assertI2T2(0x9bce40, 0x0, 0x0, 0xc8204a7cc8, 0x0)
        /usr/local/go/src/runtime/iface.go:196 fp=0xc8229c3c10 sp=0xc8229c3c08
gopkg.in/redis%2ev3.(*BoolCmd).parseReply(0xc8212286e0, 0xc820881620, 0x0, 0x0)
        /home/sergey/go/src/gopkg.in/redis.v3/command.go:365 +0xb4 fp=0xc8229c3ce8 sp=0xc8229c3c10
gopkg.in/redis%2ev3.(*baseClient).process(0xc820248660, 0x7f55771c78f0, 0xc8212286e0)
        /home/sergey/go/src/gopkg.in/redis.v3/redis.go:72 +0x337 fp=0xc8229c3db8 sp=0xc8229c3ce8
gopkg.in/redis%2ev3.(*baseClient).(gopkg.in/redis%2ev3.process)-fm(0x7f55771c78f0, 0xc8212286e0)
        /home/sergey/go/src/gopkg.in/redis.v3/redis.go:185 +0x34 fp=0xc8229c3dd8 sp=0xc8229c3db8
gopkg.in/redis%2ev3.(*commandable).Process(0xc820242708, 0x7f55771c78f0, 0xc8212286e0)
        /home/sergey/go/src/gopkg.in/redis.v3/commands.go:58 +0x34 fp=0xc8229c3df0 sp=0xc8229c3dd8
gopkg.in/redis%2ev3.(*commandable).Expire(0xc820242708, 0xc82f668030, 0xe, 0x8bb2c97000, 0x5)
        /home/sergey/go/src/gopkg.in/redis.v3/commands.go:119 +0x228 fp=0xc8229c3e98 sp=0xc8229c3df0
main.queuewatcher()
        /home/sergey/go/src/github.com/chunkhost/ua-go/ingest/main.go:93 +0x4cf fp=0xc8229c3fa0 sp=0xc8229c3e98
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc8229c3fa8 sp=0xc8229c3fa0
created by main.main
        /home/sergey/go/src/github.com/chunkhost/ua-go/ingest/main.go:59 +0x754
```

**Comment by vmihailenco** [comment]
Do you still use Go 1.5? If so then you need to upgrade to Go 1.5.1 - https://github.com/golang/go/issues/12253

**Comment by SergeyTsalkov** [comment]
I'm on 1.5, so that's probably it! Much gratitude, you rock!
