### ISSUE TITLE
after upgrading to 8.11.4, there was a crash happened in some cases.

### ISSUE THREAD

**Issue by lilien1010** [go-redis/redis#1949]
after upgrading to 8.11.4, there was a crash happened in some cases.
here is the call stack.

```

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1362a37]

goroutine 147 [running]:
github.com/go-redis/redis/v8/internal/pool.(*ConnPool).waitTurn(0xc000132280, 0x0, 0x0, 0xc0002c99d0, 0x19eb844)
	/Users/lilien/pkg/mod/github.com/go-redis/redis/v8@v8.11.4/internal/pool/pool.go:292 +0x37
github.com/go-redis/redis/v8/internal/pool.(*ConnPool).Get(0xc000132280, 0x0, 0x0, 0x6, 0x37569e0, 0xc0002c97f0)
	/Users/lilien/pkg/mod/github.com/go-redis/redis/v8@v8.11.4/internal/pool/pool.go:249 +0x58
github.com/go-redis/redis/v8.(*baseClient)._getConn(0xc00007c7a0, 0x0, 0x0, 0x203000, 0x15, 0xc0002c9840)
	/Users/lilien/pkg/mod/github.com/go-redis/redis/v8@v8.11.4/redis.go:194 +0x4c
github.com/go-redis/redis/v8.(*baseClient).getConn(0xc00007c7a0, 0x0, 0x0, 0x361ffff, 0xc0002c98c8, 0x100f53b)
	/Users/lilien/pkg/mod/github.com/go-redis/redis/v8@v8.11.4/redis.go:182 +0x66
github.com/go-redis/redis/v8.(*baseClient).withConn(0xc00007c7a0, 0x0, 0x0, 0xc0000dc600, 0x0, 0x0)
	/Users/lilien/pkg/mod/github.com/go-redis/redis/v8@v8.11.4/redis.go:274 +0x8a
github.com/go-redis/redis/v8.(*baseClient)._generalProcessPipeline(0xc00007c7a0, 0x0, 0x0, 0xc000bf8880, 0x4, 0x4, 0xc00081f180, 0x10, 0x1b55760)
	/Users/lilien/pkg/mod/github.com/go-redis/redis/v8@v8.11.4/redis.go:424 +0x113
github.com/go-redis/redis/v8.(*baseClient).generalProcessPipeline(0xc00007c7a0, 0x0, 0x0, 0xc000bf8880, 0x4, 0x4, 0xc00081f180, 0x0, 0x0)
	/Users/lilien/pkg/mod/github.com/go-redis/redis/v8@v8.11.4/redis.go:404 +0x77
github.com/go-redis/redis/v8.(*baseClient).processTxPipeline(...)
	/Users/lilien/pkg/mod/github.com/go-redis/redis/v8@v8.11.4/redis.go:396
github.com/go-redis/redis/v8.hooks.processPipeline(0xc000730d90, 0x1, 0x1, 0x0, 0x0, 0xc000bf8880, 0x4, 0x4, 0xc0002c9bd0, 0x70, ...)
	/Users/lilien/pkg/mod/github.com/go-redis/redis/v8@v8.11.4/redis.go:103 +0x32a
github.com/go-redis/redis/v8.hooks.processTxPipeline(0xc000730d90, 0x1, 0x1, 0x0, 0x0, 0xc0002b02a0, 0x2, 0x2, 0xc0002c9bd0, 0x1a2d2f4, ...)
	/Users/lilien/pkg/mod/github.com/go-redis/redis/v8@v8.11.4/redis.go:120 +0x2b7
github.com/go-redis/redis/v8.(*Client).processTxPipeline(...)
	/Users/lilien/pkg/mod/github.com/go-redis/redis/v8@v8.11.4/redis.go:604
github.com/go-redis/redis/v8.(*Pipeline).Exec(0xc000ac2550, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/lilien/pkg/mod/github.com/go-redis/redis/v8@v8.11.4/pipeline.go:115 +0x102
github.com/vmihailenco/taskq/v3/redisq.(*Queue).Release(0xc00061ccf0, 0xc00018a410, 0x0, 0x0)
```

**Comment by lilien1010** [comment]
the code is like
``` 
        .....
	pipe := q.redis.TxPipeline()
	err := pipe.XDel(msg.Ctx, q.stream, msg.ID).Err()
	if err != nil {
		return err
	}

	 pipe.ZAdd(msg.Ctx, q.zset, &redis.Z{
			Score:  float64(unixMs(tm)),
			Member: body,
		}).Err()

	_, err = pipe.Exec(msg.Ctx)
	return err
```

**Comment by lilien1010** [comment]
related to https://github.com/vmihailenco/taskq/issues/150
not sure it's on taskq or go-redis

**Comment by vmihailenco** [comment]
pool.go:292 is wait `<-ctx.Done()`. Are you using nil context?

**Comment by lilien1010** [comment]
but if `ctx` is nil,  I think `.waitTurn(0xc000132280, ` should be `.waitTurn(0xc00000000, `

**Comment by lilien1010** [comment]
reason is [here](https://github.com/vmihailenco/taskq/issues/150#issuecomment-972604193)
