### ISSUE TITLE
`LPush(string, ...string)` unexpected signal during runtime execution error

### ISSUE THREAD

**Issue by siriuszhuang** [go-redis/redis#225]
```
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0xb01dfacedebac1e pc=0xcfc6]

goroutine 9 [running]:
runtime.throw(0x34b3e0, 0x2a)
        /usr/local/Cellar/go/1.5.2/libexec/src/runtime/panic.go:527 +0x90 fp=0xc82005d6c8 sp=0xc82005d6b0
runtime.sigpanic()
        /usr/local/Cellar/go/1.5.2/libexec/src/runtime/sigpanic_unix.go:12 +0x5a fp=0xc82005d718 sp=0xc82005d6c8
runtime.getitab(0x276420, 0x2f3318, 0x1001, 0xc82011d000)
        /usr/local/Cellar/go/1.5.2/libexec/src/runtime/iface.go:86 +0x2e6 fp=0xc82005d800 sp=0xc82005d718
runtime.assertE2I2(0x276420, 0x2f3318, 0x2, 0xc82005d930, 0x4)
        /usr/local/Cellar/go/1.5.2/libexec/src/runtime/iface.go:376 +0x75 fp=0xc82005d838 sp=0xc82005d800
gopkg.in/redis%2ev3.appendArg(0xc82011d000, 0x19, 0x1000, 0x2f3318, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/zhuangsirui/.golib/src/gopkg.in/redis.v3/parser.go:94 +0x446 fp=0xc82005d9a0 sp=0xc82005d838
gopkg.in/redis%2ev3.appendArgs(0xc82011d000, 0x19, 0x1000, 0xc820016bd0, 0x3, 0x3, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/zhuangsirui/.golib/src/gopkg.in/redis.v3/parser.go:115 +0x1d2 fp=0xc82005da58 sp=0xc82005d9a0
gopkg.in/redis%2ev3.(*conn).writeCmds(0xc820018a80, 0xc82005dbe8, 0x1, 0x1, 0x0, 0x0)
        /Users/zhuangsirui/.golib/src/gopkg.in/redis.v3/conn.go:68 +0x156 fp=0xc82005db48 sp=0xc82005da58
gopkg.in/redis%2ev3.(*baseClient).process(0xc82000a840, 0x57e8a8, 0xc820010690)
        /Users/zhuangsirui/.golib/src/gopkg.in/redis.v3/redis.go:59 +0x1d2 fp=0xc82005dc18 sp=0xc82005db48
gopkg.in/redis%2ev3.(*baseClient).(gopkg.in/redis%2ev3.process)-fm(0x57e8a8, 0xc820010690)
        /Users/zhuangsirui/.golib/src/gopkg.in/redis.v3/redis.go:187 +0x34 fp=0xc82005dc38 sp=0xc82005dc18
gopkg.in/redis%2ev3.(*commandable).Process(0xc82000f148, 0x57e8a8, 0xc820010690)
        /Users/zhuangsirui/.golib/src/gopkg.in/redis.v3/commands.go:58 +0x34 fp=0xc82005dc50 sp=0xc82005dc38
gopkg.in/redis%2ev3.(*ClusterClient).process(0xc82007c1b0, 0x57e8a8, 0xc820010690)
        /Users/zhuangsirui/.golib/src/gopkg.in/redis.v3/cluster.go:152 +0x7e4 fp=0xc82005dd90 sp=0xc82005dc50
gopkg.in/redis%2ev3.(*ClusterClient).(gopkg.in/redis%2ev3.process)-fm(0x57e8a8, 0xc820010690)
        /Users/zhuangsirui/.golib/src/gopkg.in/redis.v3/cluster.go:41 +0x34 fp=0xc82005ddb0 sp=0xc82005dd90
gopkg.in/redis%2ev3.(*commandable).Process(0xc82007c1b0, 0x57e8a8, 0xc820010690)
        /Users/zhuangsirui/.golib/src/gopkg.in/redis.v3/commands.go:58 +0x34 fp=0xc82005ddc8 sp=0xc82005ddb0
gopkg.in/redis%2ev3.(*commandable).LPush(0xc82007c1b0, 0x2f11b0, 0x4, 0xc82005def0, 0x1, 0x1, 0x8)
        /Users/zhuangsirui/.golib/src/gopkg.in/redis.v3/commands.go:776 +0x31f fp=0xc82005de80 sp=0xc82005ddc8
```

It happens every time when I call `LPush` with ClusterClient.

**Comment by siriuszhuang** [comment]
I really think it's a issue. only happen when I checkout to newest master branch.

**Comment by vmihailenco** [comment]
I can't reproduce it locally. Can you provide any way to reproduce this issue?

Also you can try to disable https://github.com/go-redis/redis/blob/master/unsafe.go by using `appengine` build tag...

**Comment by vmihailenco** [comment]
Please reopen when you have more details.
