### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by evt** [go-redis/redis#256]
```
$ cat redis.go
package main

import rds "gopkg.in/redis.v3"

func main() {
	client := rds.NewClient(&rds.Options{
		// Network: "tcp",
		Addr: "192.168.33.20:6379",
	})
	if client == nil {
		panic("Redis NewClient failed")
	}

	err := client.Ping().Err()

	if err != nil {
		panic("rds.NewClient error : " + err.Error())
	}
}
```

```
$ go run redis.go
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x80dec6c]

goroutine 1 [running]:
panic(0x81c0000, 0x1850a038)
	/home/vagrant/dist/go/src/runtime/panic.go:464 +0x326
sync/atomic.AddUint64(0x18576104, 0x1, 0x0, 0x0, 0x184fe7de)
	/home/vagrant/dist/go/src/sync/atomic/asm_386.s:112 +0xc
gopkg.in/redis%2ev3.(*connPool).Get(0x185760f0, 0x0, 0x82df100, 0x0, 0x0)
	/tgo/src/gopkg.in/redis.v3/pool.go:240 +0x8a
gopkg.in/redis%2ev3.(*baseClient).conn(0x1850e350, 0x1, 0x185000d0, 0x0, 0x0)
	/tgo/src/gopkg.in/redis.v3/redis.go:23 +0x3d
gopkg.in/redis%2ev3.(*baseClient).process(0x1850e350, 0xb6c11210, 0x18518210)
	/tgo/src/gopkg.in/redis.v3/redis.go:43 +0x5c
gopkg.in/redis%2ev3.(*baseClient).(gopkg.in/redis%2ev3.process)-fm(0xb6c11210, 0x18518210)
	/tgo/src/gopkg.in/redis.v3/redis.go:189 +0x30
gopkg.in/redis%2ev3.(*commandable).Process(0x1850a21c, 0xb6c11210, 0x18518210)
	/tgo/src/gopkg.in/redis.v3/commands.go:57 +0x2e
gopkg.in/redis%2ev3.(*commandable).Ping(0x1850a21c, 0x1850a218)
	/tgo/src/gopkg.in/redis.v3/commands.go:77 +0xed
main.main()
	/tgo/src/twibo/redis.go:16 +0xb7
exit status 2
```

```
$ go version
go version go1.6 linux/386
```

Am I doing anything wrong?

**Comment by vmihailenco** [comment]
Should be fixed, thanks for the report.

**Comment by evt** [comment]
Thanks a lot! Works fine now.
