### ISSUE TITLE
Go Redis Panicking on using Eval

### ISSUE THREAD

**Issue by debraj-manna** [go-redis/redis#442]
We have a web app using Go-Redis to talk to redis. Under load around 10,000 req/sec seeing the below panic:-

```go
goroutine 1553 [running]:
panic(0x6fd8a0, 0xc42000c060)
        /usr/local/go1.7.3/src/runtime/panic.go:500 +0x1a1
gopkg.in/redis%2ev5.(*ClusterClient).Process(0xc4200107c0, 0x8cfe60, 0xc422665800, 0x0, 0x0)
        /var/lib/jenkins/jobs/CI_jSession_pkg_creation/JSession/_libs/src/gopkg.in/redis.v5/cluster.go:432 +0x5f4
gopkg.in/redis%2ev5.(*ClusterClient).Process-fm(0x8cfe60, 0xc422665800, 0x9, 0xc422665800)
        /var/lib/jenkins/jobs/CI_jSession_pkg_creation/JSession/_libs/src/gopkg.in/redis.v5/cluster.go:342 +0x3e
gopkg.in/redis%2ev5.(*cmdable).Eval(0xc4200107c0, 0xc420c77340, 0x158, 0xc4258f40c0, 0x1, 0x2, 0xc428772af0, 0x5, 0x5, 0x0)
        /var/lib/jenkins/jobs/CI_jSession_pkg_creation/JSession/_libs/src/gopkg.in/redis.v5/commands.go:1760 +0x3aa
bitbucket.org/man/session-service/redis.(*goRedisImpl).Eval(0xc42004c088, 0xc420c77340, 0x158, 0xc4258f40c0, 0x1, 0x2, 0xc428772af0, 0x5, 0x5, 0x0, ...)
        /var/lib/jenkins/jobs/CI_jSession_pkg_creation/JSession/_libs/src/bitbucket.org/man/session-service/redis/goRedisImpl.go:87 +0x165
bitbucket.org/man/session-service/redis.Eval(0xc420c77340, 0x158, 0xc4258f40c0, 0x1, 0x2, 0xc428772af0, 0x5, 0x5, 0xc428772af0, 0x6e6520, ...)
        /var/lib/jenkins/jobs/CI_jSession_pkg_creation/JSession/_libs/src/bitbucket.org/man/session-service/redis/redis_manager.go:66 +0x9e
bitbucket.org/man/session-service/persistence.evalLuaScript(0x760a40, 0x11, 0xc4258f40c0, 0x1, 0x2, 0xc428772af0, 0x5, 0x5, 0x0, 0x8000102, ...)
        /var/lib/jenkins/jobs/CI_jSession_pkg_creation/JSession/_libs/src/bitbucket.org/man/session-service/persistence/sessionStorageHelper.go:243 +0xb3
bitbucket.org/man/session-service/persistence.RunLuaScript(0x760a40, 0x11, 0xc4258f40c0, 0x1, 0x2, 0xc428772af0, 0x5, 0x5, 0xc428772af0, 0x5, ...)
        /var/lib/jenkins/jobs/CI_jSession_pkg_creation/JSession/_libs/src/bitbucket.org/man/session-service/persistence/sessionStorageHelper.go:239 +0x87
bitbucket.org/man/session-service/persistence.getSessionRolling(0xc4205f1ca7, 0x2e, 0x7530, 0xc420c7aed0, 0xc, 0xc4433208d0)
        /var/lib/jenkins/jobs/CI_jSession_pkg_creation/JSession/_libs/src/bitbucket.org/man/session-service/persistence/sessionStorageHelper.go:58 +0x28e
bitbucket.org/man/session-service/persistence.getSession(0xc4205f1ca7, 0x2e, 0x7530, 0x0, 0x0, 0x0)
        /var/lib/jenkins/jobs/CI_jSession_pkg_creation/JSession/_libs/src/bitbucket.org/man/session-service/persistence/sessionStorageHelper.go:35 +0x6c
bitbucket.org/man/session-service/persistence.GetSession(0xc4205f1ca7, 0x2e, 0x7530, 0x0, 0x0, 0x0)
        /var/lib/jenkins/jobs/CI_jSession_pkg_creation/JSession/_libs/src/bitbucket.org/man/session-service/persistence/sessionStorageJson.go:32 +0x3f
bitbucket.org/man/session-service/api.GetSession(0xc44185b200)
        /var/lib/jenkins/jobs/CI_jSession_pkg_creation/JSession/_libs/src/bitbucket.org/man/session-service/api/api.go:57 +0x384
bitbucket.org/man/session-service/routes.getDefaultRoutes.func2(0xc44185b200)
        /var/lib/jenkins/jobs/CI_jSession_pkg_creation/JSession/_libs/src/bitbucket.org/man/session-service/routes/default_routes.go:57 +0x141
github.com/buaazp/fasthttprouter.(*Router).Handler(0xc4201f2720, 0xc44185b200)
        /var/lib/jenkins/jobs/CI_jSession_pkg_creation/JSession/_libs/src/github.com/buaazp/fasthttprouter/router.go:300 +0xad5
github.com/buaazp/fasthttprouter.(*Router).Handler-fm(0xc44185b200)
        /var/lib/jenkins/jobs/CI_jSession_pkg_creation/JSession/main.go:34 +0x34
github.com/valyala/fasthttp.CompressHandlerLevel.func1(0xc44185b200)
        /var/lib/jenkins/jobs/CI_jSession_pkg_creation/JSession/_libs/src/github.com/valyala/fasthttp/server.go:345 +0x3f
github.com/valyala/fasthttp.(*Server).serveConn(0xc4200b4000, 0x8d01c0, 0xc42047ea40, 0x1, 0x101)
        /var/lib/jenkins/jobs/CI_jSession_pkg_creation/JSession/_libs/src/github.com/valyala/fasthttp/server.go:1533 +0x573
github.com/valyala/fasthttp.(*Server).(github.com/valyala/fasthttp.serveConn)-fm(0x8d01c0, 0xc42047ea40, 0xc4325d6758, 0x1)
        /var/lib/jenkins/jobs/CI_jSession_pkg_creation/JSession/_libs/src/github.com/valyala/fasthttp/server.go:1250 +0x3e
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc42000e380, 0xc4381040a0)
        /var/lib/jenkins/jobs/CI_jSession_pkg_creation/JSession/_libs/src/github.com/valyala/fasthttp/workerpool.go:210 +0xde
github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc42000e380, 0xc4381040a0, 0x6d7be0, 0xc4381040a0)
        /var/lib/jenkins/jobs/CI_jSession_pkg_creation/JSession/_libs/src/github.com/valyala/fasthttp/workerpool.go:182 +0x35
created by github.com/valyala/fasthttp.(*workerPool).getCh
        /var/lib/jenkins/jobs/CI_jSession_pkg_creation/JSession/_libs/src/github.com/valyala/fasthttp/workerpool.go:184 +0x111
```

The code that is causing the panic is making a call to redis as follows:-

```
redis.Eval(script, keys, args...).Result()
```

where,
 
- `keys` = `JJN2eed1fbdc07411e6b3093c970ed45def1481551591G`
- `args...` =  array having values like 30000, SSF_lastAccessedDate, 1481551627, SSF_expiryDate, 1481581627
- `script` having a lua script:-

```lua
if redis.call("EXISTS", KEYS[1]) == 1 then
    local keyvalues = redis.call("HGETALL", KEYS[1])
    local a = {}
    for i=2, table.getn(ARGV) do
      a[i-1] = ARGV[i]
    end
    local res = redis.call("HMSET", KEYS[1], unpack(a))
    redis.call("EXPIRE", KEYS[1], ARGV[1])  
    return keyvalues
else
    return 2 -- "Key doesn't exists"
end
```

Environment:-

- Go 1.7.2
- Redis 3.2.5
- go-redis - v5.2

This below error is coming only when we are sending lot of requests. Under 100 req/sec not seeing the issue.

**Comment by vmihailenco** [comment]
Thanks for the report - I fixed it in v5.1.3.
