### ISSUE TITLE
ClusterClient will panic when all server shutdown

### ISSUE THREAD

**Issue by winxxp** [go-redis/redis#478]
`
client := v5.NewClusterClient(&v5.ClusterOptions{
    Addrs:    []string{"127.0.0.1:7000"},
    PoolSize: 0,
})
defer client.Close()

cmd := client.ClusterNodes()
if cmd.Err() != nil {
    fmt.Println(cmd.Err())
    return
}
fmt.Println(cmd.String())
fmt.Println("wait 60s")

// now shutdown all cluster server
time.Sleep(time.Second*60)

cmd = client.ClusterNodes()
if cmd.Err() != nil {
    fmt.Println(cmd.Err())
    return
}
`

`
--- FAIL: TestRedislibV5 (51.83s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4dec46]

goroutine 4 [running]:
panic(0x5fab80, 0xc420012090)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc420082180)
	/usr/local/go/src/testing/testing.go:579 +0x25d
panic(0x5fab80, 0xc420012090)
	/usr/local/go/src/runtime/panic.go:458 +0x243
vendor/gopkg.in/redis%2ev5.(*ClusterClient).Process(0xc420014800, 0x7231a0, 0xc4200620f0, 0x0, 0x0)
	/home/hl/cache/src/vendor/gopkg.in/redis.v5/cluster.go:434 +0xbd6
vendor/gopkg.in/redis%2ev5.(*ClusterClient).Process-fm(0x7231a0, 0xc4200620f0, 0x2, 0xc4200620f0)
	/home/hl/cache/src/vendor/gopkg.in/redis.v5/cluster.go:346 +0x3e
vendor/gopkg.in/redis%2ev5.(*cmdable).ClusterNodes(0xc420014800, 0x1)
	/home/hl/cache/src/vendor/gopkg.in/redis.v5/commands.go:1875 +0x132
iscp.huawei.com/cache/monitor/node.TestRedislibV5(0xc420082180)
	/home/hl/cache/src/iscp.huawei.com/cache/monitor/node/node_test.go:68 +0x277
testing.tRunner(0xc420082180, 0x654f70)
	/usr/local/go/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:646 +0x2ec

`

**Comment by vmihailenco** [comment]
Can you try latest version? cluster.go:346 is an empty line on master,
