### ISSUE TITLE
Bad interface conversion in PubSub

### ISSUE THREAD

**Issue by jinroh** [go-redis/redis#715]
Since PR #710, we have seen the following error in the pubsub module:

```
panic: interface conversion: interface {} is *errors.errorString, not string
goroutine 163 [running]:
github.com/go-redis/redis.(*PubSub).newMessage(0xc420b1e200, 0xe21080, 0xc420aba020, 0x0, 0xc420ae6fc0, 0xc4204a0f00, 0xc420ff1ac0)
go-redis/redis/pubsub.go:253 +0xb32
github.com/go-redis/redis.(*PubSub).ReceiveTimeout(0xc420b1e200, 0x12a05f200, 0x0, 0xc4215643f0, 0x0, 0x0)
go-redis/redis/pubsub.go:293 +0x11a
github.com/go-redis/redis.(*PubSub).receiveMessage(0xc420b1e200, 0x12a05f200, 0xc421564301, 0x752abf, 0x1)
go-redis/redis/pubsub.go:313 +0x46
github.com/go-redis/redis.(*PubSub).ReceiveMessage(0xc420b1e200, 0xc420ae6fc0, 0x0, 0x0)
go-redis/redis/pubsub.go:307 +0x3a
github.com/go-redis/redis.(*PubSub).Channel.func1.1(0xc420b1e200)
go-redis/redis/pubsub.go:360 +0x2f
created by github.com/go-redis/redis.(*PubSub).Channel.func1
go-redis/redis/pubsub.go:358 +0x7e
```

The type conversion [`pubsub.go:253`](https://github.com/go-redis/redis/blob/ea4d6c3490285e115c475c81dfb9a4e7a2c4bcae/pubsub.go#L253) is failing in a failure case, expecting a string instead of an error.

I wonder if the changes made in #710 could have other impact of this type.

**Comment by vmihailenco** [comment]
Thanks for the report - should be fixed in v6.9.1
