### ISSUE TITLE
writebuffer appendstring panic

### ISSUE THREAD

**Issue by kensomanpow** [go-redis/redis#727]
i encountered a problem when I trying to use cmd.Val(), 
could anyone give some advise to figure out what did I happen?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x45d1ec]

goroutine 12438410 [running]:
github.com/go-redis/redis/internal/proto.(*WriteBuffer).AppendString(0xc421f909c0, 0x0, 0x3f)
        /Users/xxxxxx/go/src/github.com/go-redis/redis/internal/proto/write_buffer.go:93 +0x138
github.com/go-redis/redis/internal/proto.(*WriteBuffer).append(0xc421f909c0, 0xd06f40, 0xc423da4250, 0x0, 0x0)
        /Users/xxxxxx/go/src/github.com/go-redis/redis/internal/proto/write_buffer.go:41 +0x5bc
github.com/go-redis/redis/internal/proto.(*WriteBuffer).Append(0xc421f909c0, 0xc424c545e0, 0x2, 0x2, 0x0, 0x13cef40)
        /Users/xxxxxx/go/src/github.com/go-redis/redis/internal/proto/write_buffer.go:29 +0x12b
github.com/go-redis/redis.writeCmd(0xc422de1f80, 0xc4220fadb0, 0x1, 0x1, 0x0, 0x38)
        /Users/xxxxxx/go/src/github.com/go-redis/redis/command.go:49 +0x89
github.com/go-redis/redis.(*baseClient).defaultProcess(0xc42033e240, 0x1383b60, 0xc420ab0240, 0x40, 0xda4de0)
        /Users/xxxxxx/go/src/github.com/go-redis/redis/redis.go:146 +0x167
github.com/go-redis/redis.(*baseClient).Process(0xc42033e240, 0x1383b60, 0xc420ab0240, 0xc420ab0240, 0xc424c545e0)
        /Users/xxxxxx/go/src/github.com/go-redis/redis/redis.go:127 +0x82
github.com/go-redis/redis.(*baseClient).Process-fm(0x1383b60, 0xc420ab0240, 0x2, 0xc420ab0240)
        /Users/xxxxxx/go/src/github.com/go-redis/redis/redis.go:88 +0x3e
github.com/go-redis/redis.(*cmdable).HGetAll(0xc42033e278, 0x0, 0x3f, 0xc422bcc1e0)
        /Users/xxxxxx/go/src/github.com/go-redis/redis/commands.go:865 +0xf0
github.com/go-redis/redis.(*StringStringMapCmd).Val(...)
        /Users/xxxxxx/go/src/git.xxxxx.com/RD/gamelib/redis/user/user.go:162
git.xxxxx.com/RD/gamelib/redis/user.Get.func1(0xc42033e240, 0xed43d8, 0xc42236a040)
        /Users/xxxxxx/go/src/git.xxxxx.com/RD/gamelib/redis/user/user.go:162 +0x48d
github.com/go-redis/redis.(*ClusterClient).ForEachMaster.func1(0xc42236a040, 0xc421f48000, 0xc422908000, 0xc420332300)
        /Users/xxxxxx/go/src/github.com/go-redis/redis/cluster.go:702 +0x5d
created by github.com/go-redis/redis.(*ClusterClient).ForEachMaster
        /Users/xxxxxx/go/src/github.com/go-redis/redis/cluster.go:700 +0x114

```

**Comment by vmihailenco** [comment]
How do you use `ForEachMaster`?

**Comment by kensomanpow** [comment]
i used `ForEachMaster` to scan keys in master nodes, then trying to get result from the keys, then happened panic error

**Comment by vmihailenco** [comment]
Please provide the code.

**Comment by kensomanpow** [comment]
here is the code

```
con.ForEachMaster(func(client *goredis.Client) error {
    if betSerials == nil {
        redisKeys, _ = client.Keys(redisKey.KeyGen(keys.UserBetSerial)).Result()
        if len(redisKeys) > 0 {
            betSerials, _ = client.HGetAll(redisKeys[0]).Result()
        }
    }
    return nil
})
```

**Comment by vmihailenco** [comment]
Code looks fine. From the backtrace it looks like you are using old go-redis version - please try to upgrade to master.

**Comment by kensomanpow** [comment]
I see, i will use the latest version to do more test. thank you @vmihailenco

**Comment by kensomanpow** [comment]
After I running on the new version. There isn't appear the error again. so I close this issue. Thanks to @vmihailenco again.
