### ISSUE TITLE
panic on Close

### ISSUE THREAD

**Issue by pierrre** [go-redis/redis#888]
Hello

I noticed that the client panics when I try to close it.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8c7f26]

goroutine 20 [running]:
github.com/org/project/vendor/github.com/go-redis/redis.(*sentinelFailover).closeSentinel(0xc0001b7180, 0xb58a10, 0xc0001b71b4)
    /home/travis/gopath/src/github.com/org/project/vendor/github.com/go-redis/redis/sentinel.go:308 +0x26
github.com/org/project/vendor/github.com/go-redis/redis.(*sentinelFailover).Close(0xc0001b7180, 0x0, 0x0)
    /home/travis/gopath/src/github.com/org/project/vendor/github.com/go-redis/redis/sentinel.go:184 +0x76
github.com/org/project/vendor/github.com/go-redis/redis.NewFailoverClient.func1(0x0, 0x0)
    /home/travis/gopath/src/github.com/org/project/vendor/github.com/go-redis/redis/sentinel.go:94 +0x2a
github.com/org/project/vendor/github.com/go-redis/redis.(*baseClient).Close(0xc00023af50, 0x0, 0x0)
    /home/travis/gopath/src/github.com/org/project/vendor/github.com/go-redis/redis/redis.go:213 +0x9a
```

Go version: 1.11.1 linux amd64
go-redis version: fa76dd0e87967c95e6f7bef33a230ed2c263fe2d (the tag v6.14.1 is a little bit old)

Any idea ?
I think we should check that https://github.com/go-redis/redis/blob/fa76dd0e87967c95e6f7bef33a230ed2c263fe2d/sentinel.go#L308 is not nil before using it. WDYT ?

Thanks

**Comment by vmihailenco** [comment]
Yes, you are right. I've sent a fix.

**Comment by pierrre** [comment]
thank you :+1:

**Comment by pierrre** [comment]
could you release a new tag for this fix ?

**Comment by vmihailenco** [comment]
Tagged v6.14.2

**Comment by pierrre** [comment]
Thank you ! :100:
